# Generated by Django 4.2.1 on 2023-05-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
