# Generated by Django 4.2.1 on 2023-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0004_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
